
[unstable]
build-std = ["core", "compiler_builtins"]
buid-std-features = ["compiler-builtins-mem"]


[build]
target = "x86_64-os_lab.json"

# [target.'cfg(target_os = "linux")']
# rustflags = ["-C", "link-arg=-nostartfiles"]
[target.'cfg(target_os = "none")']
runner = "bootimage runner"



